codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: 50%
        threshold: 1%
      library:
        target: 30%
        threshold: 1%
        flags:
          - library
        paths:
          - "src/**"
          - "plugin/src/**"
      example:
        target: 50%
        threshold: 1%
        flags:
          - example
        paths:
          - "example/screens/**"
          - "example/components/**"
    patch:
      default:
        target: 50%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true

flags:
  library:
    paths:
      - src/
      - plugin/src/
    carryforward: false
  example:
    paths:
      - example/screens/
      - example/components/
    carryforward: false

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "example/**"
  - "example-expo/**"
  - "docs/**"
  - "scripts/**"
  - "nitrogen/generated/**"
  - "lib/**"