codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        paths:
          - "src/**"
    patch:
      default:
        target: 70%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "example/**"
  - "example-expo/**"
  - "docs/**"
  - "scripts/**"
  - "nitrogen/generated/**"
  - "lib/**"