name: 🐛 Bug report
description: Report a reproducible bug or regression in this library.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # Bug report

        👋 Hi!

        **Please fill the following carefully before opening a new issue ❗**
        *(Your issue may be closed if it doesn't provide the required pieces of information)*
  - type: checkboxes
    attributes:
      label: Before submitting a new issue
      description: Please perform simple checks first.
      options:
        - label: I tested using the latest version of the library, as the bug might be already fixed.
          required: true
        - label: I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
          required: true
        - label: I checked for possible duplicate issues, with possible answers.
          required: true
  - type: textarea
    id: summary
    attributes:
      label: Bug summary
      description: |
        Provide a clear and concise description of what the bug is.
        If needed, you can also provide other samples: error messages / stack traces, screenshots, gifs, etc.
    validations:
      required: true
  - type: input
    id: library-version
    attributes:
      label: Library version
      description: What version of the library are you using?
      placeholder: 'x.x.x'
    validations:
      required: true
  - type: input
    id: react-native-version
    attributes:
      label: React Native version
      description: Exact version from your app (e.g., 0.73.7). If using Expo, include SDK version.
      placeholder: '0.73.7 (Expo SDK 51)'
    validations:
      required: true
  - type: dropdown
    id: nitro-installed
    attributes:
      label: Is `react-native-nitro-modules` installed?
      description: This library relies on Nitro. Indicate whether `react-native-nitro-modules` is installed and configured in your app.
      options:
        - Yes
        - No
        - Not sure
    validations:
      required: true
  - type: input
    id: nitro-version
    attributes:
      label: `react-native-nitro-modules` version
      description: Optional. If installed, provide the version (e.g., output of `npm ls react-native-nitro-modules` or `yarn why react-native-nitro-modules`).
      placeholder: 'x.x.x'
    validations:
      required: false
  - type: dropdown
    id: platforms
    attributes:
      label: Platform(s) affected
      description: Select all platforms where you can reproduce the issue.
      multiple: true
      options:
        - iOS
        - Android
    validations:
      required: true
  - type: textarea
    id: react-native-info
    attributes:
      label: Environment info
      description: Optional. Run `npx react-native info` and paste results for more context.
      render: shell
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        You must provide a clear list of steps and code to reproduce the problem.
      value: |
        1. …
        2. …
    validations:
      required: true
  - type: textarea
    id: expected-results
    attributes:
      label: Expected results
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-results
    attributes:
      label: Actual results
      description: Describe what actually happened.
    validations:
      required: true
  - type: textarea
    id: snack-or-minimal-code-example
    attributes:
      label: Snack or minimal code example
      description: |
        Please provide a Snack (https://snack.expo.io/) or link to a minimal code example that reproduces the issue.
        **Please note: that a full reproduction environment is more helpful than just code snippets.**
      placeholder: 'https://github.com/...'
