name: CI - Test
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-test.yml'
      - '.github/actions/**'
      - 'src/**/__tests__/**'
      - 'src/**/*.test.*'
      - 'jest.config.*'
      - 'jest.setup.*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci-test.yml'
      - '.github/actions/**'
      - 'src/**/__tests__/**'
      - 'src/**/*.test.*'
      - 'jest.config.*'
      - 'jest.setup.*'
  merge_group:
    types:
      - checks_requested

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup


      - name: Run library tests
        run: yarn test:ci
      
      - name: Run example tests
        run: yarn workspace rn-iap-example test --coverage
      
      - name: Upload library coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hyochan/react-native-iap
          files: ./coverage/lcov.info
          flags: library
          name: library-coverage
          fail_ci_if_error: false
      
      - name: Upload example coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hyochan/react-native-iap
          files: ./example/coverage/lcov.info
          flags: example
          name: example-coverage
          fail_ci_if_error: false